# Generated by Django 5.2.17 on 2026-10-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_user/'),
        ),
    ]
