# Generated by Django 5.2.17 on 2026-10-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_remove_user_profile_picture_user_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='poster',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatar/'),
        ),
    ]
