// Matches Apps/Theater/models.py + TheaterSerializer / ScreenSerializer / SeatSerializer

export type SeatType = "REGULAR" | "PREMIUM" | "VIP";

export interface Seat {
  id: number;
  row: string;        // 'A', 'B', 'C'...
  number: number;      // 1, 2, 3...
  seat_type: SeatType;
}

export interface Screen {
  id: number;
  theater: number;      // theater id (writable — send just the id when creating)
  name: string;          // e.g. "Screen 1", "IMAX"
  total_rows: number;
  seats_per_row: number;
  seats: Seat[];          // nested, read-only — auto-generated by the backend
}

export interface Theater {
  id: number;
  name: string;
  city: string;
  address: string;
  phone_number: string | null;
  manager: number | null;     // user id of the THEATER_MANAGER, or null
  manager_name: string | null; // read-only, from manager.get_full_name()
  is_active: boolean;
  created_at: string;           // ISO datetime string
  screens: Screen[];             // nested, read-only
}

// Payload shapes for forms — screens/seats are never created directly
// from a Theater form; a screen is created separately via POST /api/screens
// (its seats auto-generate on the backend), and seats are never POSTed at all.
export interface TheaterPayload {
  name: string;
  city: string;
  address: string;
  phone_number?: string;
  manager?: number | null;
  is_active?: boolean;
}

export interface ScreenPayload {
  theater: number;
  name: string;
  total_rows: number;
  seats_per_row: number;
}